// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: api/v1/proto/urls.proto

package urls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw string `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *ShortURLRequest) Reset() {
	*x = ShortURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLRequest) ProtoMessage() {}

func (x *ShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLRequest.ProtoReflect.Descriptor instead.
func (*ShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type ShortURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortURLResponse) Reset() {
	*x = ShortURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLResponse) ProtoMessage() {}

func (x *ShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLResponse.ProtoReflect.Descriptor instead.
func (*ShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url []*BatchURLsRequest_URL `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
}

func (x *BatchURLsRequest) Reset() {
	*x = BatchURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLsRequest) ProtoMessage() {}

func (x *BatchURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLsRequest.ProtoReflect.Descriptor instead.
func (*BatchURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{2}
}

func (x *BatchURLsRequest) GetUrl() []*BatchURLsRequest_URL {
	if x != nil {
		return x.Url
	}
	return nil
}

type BatchURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchedUrls []*BatchURLsResponse_URL `protobuf:"bytes,1,rep,name=batched_urls,json=batchedUrls,proto3" json:"batched_urls,omitempty"`
}

func (x *BatchURLsResponse) Reset() {
	*x = BatchURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLsResponse) ProtoMessage() {}

func (x *BatchURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLsResponse.ProtoReflect.Descriptor instead.
func (*BatchURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{3}
}

func (x *BatchURLsResponse) GetBatchedUrls() []*BatchURLsResponse_URL {
	if x != nil {
		return x.BatchedUrls
	}
	return nil
}

type GetShortenedURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *GetShortenedURLRequest) Reset() {
	*x = GetShortenedURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortenedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenedURLRequest) ProtoMessage() {}

func (x *GetShortenedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenedURLRequest.ProtoReflect.Descriptor instead.
func (*GetShortenedURLRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortenedURLRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetShortenedURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl *GetShortenedURLResponse_ShortenedURL `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *GetShortenedURLResponse) Reset() {
	*x = GetShortenedURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortenedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenedURLResponse) ProtoMessage() {}

func (x *GetShortenedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenedURLResponse.ProtoReflect.Descriptor instead.
func (*GetShortenedURLResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortenedURLResponse) GetShortUrl() *GetShortenedURLResponse_ShortenedURL {
	if x != nil {
		return x.ShortUrl
	}
	return nil
}

type ListURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListURLsRequest) Reset() {
	*x = ListURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsRequest) ProtoMessage() {}

func (x *ListURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsRequest.ProtoReflect.Descriptor instead.
func (*ListURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{6}
}

type ListURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectedUrls []*ListURLsResponse_URL `protobuf:"bytes,1,rep,name=collected_urls,json=collectedUrls,proto3" json:"collected_urls,omitempty"`
}

func (x *ListURLsResponse) Reset() {
	*x = ListURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsResponse) ProtoMessage() {}

func (x *ListURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsResponse.ProtoReflect.Descriptor instead.
func (*ListURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{7}
}

func (x *ListURLsResponse) GetCollectedUrls() []*ListURLsResponse_URL {
	if x != nil {
		return x.CollectedUrls
	}
	return nil
}

type DelURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slugs []string `protobuf:"bytes,1,rep,name=slugs,proto3" json:"slugs,omitempty"`
}

func (x *DelURLsRequest) Reset() {
	*x = DelURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelURLsRequest) ProtoMessage() {}

func (x *DelURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelURLsRequest.ProtoReflect.Descriptor instead.
func (*DelURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{8}
}

func (x *DelURLsRequest) GetSlugs() []string {
	if x != nil {
		return x.Slugs
	}
	return nil
}

type DelURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelURLsResponse) Reset() {
	*x = DelURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelURLsResponse) ProtoMessage() {}

func (x *DelURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelURLsResponse.ProtoReflect.Descriptor instead.
func (*DelURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{9}
}

type BatchURLsRequest_URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw    string `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	CorrId string `protobuf:"bytes,2,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
}

func (x *BatchURLsRequest_URL) Reset() {
	*x = BatchURLsRequest_URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchURLsRequest_URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLsRequest_URL) ProtoMessage() {}

func (x *BatchURLsRequest_URL) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLsRequest_URL.ProtoReflect.Descriptor instead.
func (*BatchURLsRequest_URL) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BatchURLsRequest_URL) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *BatchURLsRequest_URL) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

type BatchURLsResponse_URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CorrId   string `protobuf:"bytes,2,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
}

func (x *BatchURLsResponse_URL) Reset() {
	*x = BatchURLsResponse_URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchURLsResponse_URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLsResponse_URL) ProtoMessage() {}

func (x *BatchURLsResponse_URL) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLsResponse_URL.ProtoReflect.Descriptor instead.
func (*BatchURLsResponse_URL) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BatchURLsResponse_URL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *BatchURLsResponse_URL) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

type GetShortenedURLResponse_ShortenedURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrId    string `protobuf:"bytes,2,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
	Raw       string `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	Slug      string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Value     string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	IsDeleted bool   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
}

func (x *GetShortenedURLResponse_ShortenedURL) Reset() {
	*x = GetShortenedURLResponse_ShortenedURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortenedURLResponse_ShortenedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenedURLResponse_ShortenedURL) ProtoMessage() {}

func (x *GetShortenedURLResponse_ShortenedURL) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenedURLResponse_ShortenedURL.ProtoReflect.Descriptor instead.
func (*GetShortenedURLResponse_ShortenedURL) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetShortenedURLResponse_ShortenedURL) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetShortenedURLResponse_ShortenedURL) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

func (x *GetShortenedURLResponse_ShortenedURL) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *GetShortenedURLResponse_ShortenedURL) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetShortenedURLResponse_ShortenedURL) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetShortenedURLResponse_ShortenedURL) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ListURLsResponse_URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw      string `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	ShortUrl string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ListURLsResponse_URL) Reset() {
	*x = ListURLsResponse_URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_urls_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListURLsResponse_URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsResponse_URL) ProtoMessage() {}

func (x *ListURLsResponse_URL) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_urls_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsResponse_URL.ProtoReflect.Descriptor instead.
func (*ListURLsResponse_URL) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_urls_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListURLsResponse_URL) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *ListURLsResponse_URL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_api_v1_proto_urls_proto protoreflect.FileDescriptor

var file_api_v1_proto_urls_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75,
	0x72, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x72, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x75, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x1a, 0x30, 0x0a,
	0x03, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x72, 0x49, 0x64, 0x22,
	0x93, 0x01, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x72,
	0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x0b, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x1a, 0x3b, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x72, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6f, 0x72, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x22, 0x83, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52,
	0x4c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x1a, 0x9b, 0x01, 0x0a, 0x0c,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x72, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x6c, 0x75, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8e, 0x01, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x73, 0x1a, 0x34, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x77,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x26, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x6c, 0x75, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x6c, 0x75, 0x67, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x55, 0x52, 0x4c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x94, 0x01, 0x0a, 0x0d, 0x55, 0x52, 0x4c,
	0x73, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x08, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xa5, 0x01, 0x0a, 0x0c, 0x55, 0x52, 0x4c, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64,
	0x55, 0x52, 0x4c, 0x12, 0x1f, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x52,
	0x4c, 0x73, 0x12, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4b, 0x0a, 0x0b, 0x55, 0x52, 0x4c, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x55, 0x52, 0x4c,
	0x73, 0x12, 0x17, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x55,
	0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x75, 0x72, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_v1_proto_urls_proto_rawDescOnce sync.Once
	file_api_v1_proto_urls_proto_rawDescData = file_api_v1_proto_urls_proto_rawDesc
)

func file_api_v1_proto_urls_proto_rawDescGZIP() []byte {
	file_api_v1_proto_urls_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_urls_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_proto_urls_proto_rawDescData)
	})
	return file_api_v1_proto_urls_proto_rawDescData
}

var file_api_v1_proto_urls_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_v1_proto_urls_proto_goTypes = []interface{}{
	(*ShortURLRequest)(nil),                      // 0: urls.v1.ShortURLRequest
	(*ShortURLResponse)(nil),                     // 1: urls.v1.ShortURLResponse
	(*BatchURLsRequest)(nil),                     // 2: urls.v1.BatchURLsRequest
	(*BatchURLsResponse)(nil),                    // 3: urls.v1.BatchURLsResponse
	(*GetShortenedURLRequest)(nil),               // 4: urls.v1.GetShortenedURLRequest
	(*GetShortenedURLResponse)(nil),              // 5: urls.v1.GetShortenedURLResponse
	(*ListURLsRequest)(nil),                      // 6: urls.v1.ListURLsRequest
	(*ListURLsResponse)(nil),                     // 7: urls.v1.ListURLsResponse
	(*DelURLsRequest)(nil),                       // 8: urls.v1.DelURLsRequest
	(*DelURLsResponse)(nil),                      // 9: urls.v1.DelURLsResponse
	(*BatchURLsRequest_URL)(nil),                 // 10: urls.v1.BatchURLsRequest.URL
	(*BatchURLsResponse_URL)(nil),                // 11: urls.v1.BatchURLsResponse.URL
	(*GetShortenedURLResponse_ShortenedURL)(nil), // 12: urls.v1.GetShortenedURLResponse.ShortenedURL
	(*ListURLsResponse_URL)(nil),                 // 13: urls.v1.ListURLsResponse.URL
}
var file_api_v1_proto_urls_proto_depIdxs = []int32{
	10, // 0: urls.v1.BatchURLsRequest.url:type_name -> urls.v1.BatchURLsRequest.URL
	11, // 1: urls.v1.BatchURLsResponse.batched_urls:type_name -> urls.v1.BatchURLsResponse.URL
	12, // 2: urls.v1.GetShortenedURLResponse.short_url:type_name -> urls.v1.GetShortenedURLResponse.ShortenedURL
	13, // 3: urls.v1.ListURLsResponse.collected_urls:type_name -> urls.v1.ListURLsResponse.URL
	0,  // 4: urls.v1.URLsShortener.ShortURL:input_type -> urls.v1.ShortURLRequest
	2,  // 5: urls.v1.URLsShortener.BatchURLs:input_type -> urls.v1.BatchURLsRequest
	4,  // 6: urls.v1.URLsProvider.GetShortenedURL:input_type -> urls.v1.GetShortenedURLRequest
	6,  // 7: urls.v1.URLsProvider.ListURLs:input_type -> urls.v1.ListURLsRequest
	8,  // 8: urls.v1.URLsDeleter.DelURLs:input_type -> urls.v1.DelURLsRequest
	1,  // 9: urls.v1.URLsShortener.ShortURL:output_type -> urls.v1.ShortURLResponse
	3,  // 10: urls.v1.URLsShortener.BatchURLs:output_type -> urls.v1.BatchURLsResponse
	5,  // 11: urls.v1.URLsProvider.GetShortenedURL:output_type -> urls.v1.GetShortenedURLResponse
	7,  // 12: urls.v1.URLsProvider.ListURLs:output_type -> urls.v1.ListURLsResponse
	9,  // 13: urls.v1.URLsDeleter.DelURLs:output_type -> urls.v1.DelURLsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_proto_urls_proto_init() }
func file_api_v1_proto_urls_proto_init() {
	if File_api_v1_proto_urls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_proto_urls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortenedURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortenedURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchURLsRequest_URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchURLsResponse_URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortenedURLResponse_ShortenedURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_urls_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListURLsResponse_URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_proto_urls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_v1_proto_urls_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_urls_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_urls_proto_msgTypes,
	}.Build()
	File_api_v1_proto_urls_proto = out.File
	file_api_v1_proto_urls_proto_rawDesc = nil
	file_api_v1_proto_urls_proto_goTypes = nil
	file_api_v1_proto_urls_proto_depIdxs = nil
}
